{% set name = "pytest-reportportal" %}
{% set version = "5.4.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0bda05ef674d934ac423d62c5c494970b68de1a0cfc13453a6e2efe4c9bd9ef8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=68.0.0
    - setuptools-scm
    - wheel ==0.40.0
  run:
    - aenum >=3.1.0
    - dill >=0.3.6
    - pytest >=3.8.0
    - python >={{ python_min }}
    - reportportal-client >=5.5.10,<5.6.dev0
    - requests


test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
