{% set name = "pytest-reportportal" %}
{% set version = "5.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 495d117356aaee1b12dc653fdb9b5cc12642650bd623047a83cca80dd94fe143

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=68.0.0
    - setuptools-scm
    - wheel ==0.40.0
  run:
    - aenum >=3.1.0
    - dill >=0.3.6
    - pytest >=3.8.0
    - python >=3.7
    - reportportal-client >=5.5.9,<5.6.dev0

test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
