{% set name = "pytest-reportportal" %}
{% set version = "5.1.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-reportportal-{{ version }}.tar.gz
  sha256: edfc7b67a80ef61109248ccb44ad72ec7b3a5c6747c8567d0730c249681b0803

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=40.0
    - setuptools-scm
    - wheel ==0.37.1
  run:
    - aenum >=3.1.0
    - dill >=0.2.7.1
    - pytest >=3.8.0
    - python >=3.6
    - reportportal-client ==5.3.4
    - requests >=2.27.1
    - six >=1.15.0

test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
