{% set name = "pytest-reportportal" %}
{% set version = "5.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bb5d3d146933bf1dd407cb4c003952756ba63a5a093ce231a2ba3755a42364b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=68.0.0
    - setuptools-scm
    - wheel ==0.40.0
  run:
    - aenum >=3.1.0
    - dill >=0.3.6
    - pytest >=3.8.0
    - python >=3.7
    - reportportal-client >=5.5.7,<5.6.dev0
    - requests >=2.28.0

test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
