{% set name = "pytest-reportportal" %}
{% set version = "5.1.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-reportportal-{{ version }}.tar.gz
  sha256: 5eb735e3a469f05687a9b57e0569e38f88427fb5b3586dec5a756f4fda9ab61c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=40.0
    - setuptools-scm
  run:
    - aenum >=3.1.0
    - dill >=0.2.7.1
    - pytest >=3.8.0
    - python >=3.6
    - reportportal-client ==5.3.5
    - requests >=2.27.1
    - six >=1.16.0
    
test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
