{% set name = "pytest-reportportal" %}
{% set version = "5.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-reportportal-{{ version }}.tar.gz
  sha256: 2f269c362f82af038b2ca3b25050b0b968f2557b4a739c9c0e83276e1ec2bb50

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=68.0.0
    - setuptools-scm
    - wheel ==0.40.0
  run:
    - aenum >=3.1.0
    - dill >=0.3.6
    - pytest >=3.8.0
    - python >=3.7
    - reportportal-client ==5.4.1
    - requests >=2.27.1
    - six >=1.16.0

test:
  imports:
    - pytest_reportportal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/reportportal/agent-python-pytest
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
