schema_version: 1

context:
  name: pytest-reportportal
  version: "5.6.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 823a6e34fa7515d914d401c957130b605e9b8da56ce19eb44f468c0fa681e914

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=68.0.0
    - setuptools-scm
    - wheel ==0.40.0
  run:
    - aenum ==3.1.17
    - dill >=0.3.6
    - pytest >=4.6.10
    - python >=${{ python_min }}
    - reportportal-client ==5.7.1

tests:
  - python:
      imports:
        - pytest_reportportal
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Agent for Reporting results of tests to the Report Portal
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/reportportal/agent-python-pytest

extra:
  recipe-maintainers:
    - thewchan
